apiVersion: skaffold/v4beta9
kind: Config
build:
  artifacts:
    - image: auth-service
      context: .
      sync:
        manual:
          - src: apps/auth-service/src/**/*.ts
            dest: .
      docker:
        dockerfile: Dockerfile.dev
        buildArgs:
          service: "auth-service"
    - image: account-service
      context: .
      sync:
        manual:
          - src: apps/account-service/src/**/*.ts
            dest: .
      docker:
        dockerfile: Dockerfile.dev
        buildArgs:
          service: "account-service"
    - image: product-service
      context: .
      sync:
        manual:
          - src: apps/product-service/src/**/*.ts
            dest: .
      docker:
        dockerfile: Dockerfile.dev
        buildArgs:
          service: "product-service"
  local:
    push: false
manifests:
  rawYaml:
    - ./infra/k8s/nats.yaml
    - ./infra/k8s/auth.yaml
    - ./infra/k8s/account.yaml
    - ./infra/k8s/product.yaml
    - ./infra/k8s/ingress-nginx.yaml
deploy:
  kubectl: {}