apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: auth-service
          env:
           - name: JWT_SECRET
             value: 2813d2ae3c3af50fc146ac27efc605a33f7702736d574af19c8b9c0d2c09b08b
           - name: POSTGRES_DB
             value: auth-db
           - name: POSTGRES_USER
             value: vuk
           - name: POSTGRES_PASSWORD
             value: test1234
---
apiVersion: v1
kind: Service
metadata:
  name: auth-srv
spec:
  selector:
    app: auth
  ports:
    - name: auth
      protocol: TCP
      port: 3001
      targetPort: 3001