apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-service
  annotations:
    nginx.ingress.kubernetes.io/use-regex: 'true'
spec:
  ingressClassName: nginx
  tls:
    - hosts:
      - web-shop.dev
      secretName: webshop-cert
  rules:
    - host: web-shop.dev
      http:
        paths:
          - path: /api/auth/?(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: auth-srv
                port:
                  number: 3001
          - path: /api/account/?(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: account-srv
                port:
                  number: 3001
          - path: /api/browse/?(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: product-srv
                port:
                  number: 3001
          - path: /(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: next-srv
                port:
                  number: 3001