apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pact-postgres-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
apiVersion: v1
kind: Secret
metadata:
  name: pact-postgres-password
type: Opaque
data:
  password: cGFzc3dvcmQ=

---
apiVersion: v1
kind: Service
metadata:
  name: pact-postgres
spec:
  type: ClusterIP
  ports:
  - port: 5432
  selector:
    app: pact-postgres

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pact-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pact-postgres
  template:
    metadata:
      labels:
        app: pact-postgres
    spec:
      containers:
      - name: pact-postgres
        image: postgres:13
        env:
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: pact-postgres-password
              key: password
        ports:
        - containerPort: 5432
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: postgres-storage
      volumes:
      - name: postgres-storage
        persistentVolumeClaim:
          claimName: pact-postgres-pvc
